### ISSUE TITLE
No such file or directory pgsx.mk 

### ISSUE THREAD

**Issue by csheffo** [timescale/homebrew-tap#1]
Getting the following error when trying to install with homebrew: 

Makefile:67: /usr/local/lib/postgresql/pgxs/src/makefiles/pgxs.mk: No such file or directory
make: *** No rule to make target `/usr/local/lib/postgresql/pgxs/src/makefiles/pgxs.mk'.  Stop.

I had a previous installation of postgres that I deleted before running this ('which postgresql' is coming back clean in the command line, although psql is still in my path) 

Any advice would be greatly appreciated!

**Comment by RobAtticus** [comment]
Sorry to hear that. Did homebrew attempt to install a postgres 9.6 before timescaledb?, i.e., `which postgres` should no longer be empty (note: `postgres` not `postgresql`). It seems like postgres is either not installed or not in the location its expecting.

**Comment by csheffo** [comment]
Looks like homebrew didn't try to install postgres first - which it should have going by the documentation.

**Comment by RobAtticus** [comment]
Yes it's listed as a dependency so it should. You can try installing it separately, or removing TimescaleDB and retrying.

If it still doesn't work, can you list the output of `brew --version`? I will investigate further.

**Comment by csheffo** [comment]
Just tried installing postgres on it's own first with brew and got this warning: postgresql-9.6.3 already installed, it's just not linked.

I had 9.6.1 before so it seems like the timescale installer did do something there. Still getting the same no file or directory error when I try to install timescale after that.   I have brew version 1.2.1

Thanks for looking into this!

**Comment by RobAtticus** [comment]
Okay, sounds like doing `brew link postgresql` or `brew link --force postgresql`. My suspicion is your old Postgres install left some files (like psql) around that brew doesn't want to overwrite unless you tell it to. Assuming there's no reason not to overwrite those old binaries, one of those two commands should work and then you can try installing timescaledb again.

**Comment by csheffo** [comment]
Tried both of those commands and still getting this error:

Linking /usr/local/Cellar/postgresql/9.6.3...
Error: Could not symlink lib/pkgconfig/libecpg.pc
/usr/local/lib/pkgconfig is not writable.

**Comment by RobAtticus** [comment]
Looking up that error, I found this StackOverflow post:
https://stackoverflow.com/questions/27784545/brew-error-could-not-symlink-path-is-not-writable

Namely this part:
"Start with `brew doctor` which will show you errors with your brew setup.

You might see something like this: "Warning: /usr/local/lib/pkgconfig isn't writable."

It will give you the advice that: "You should probably chown /usr/local/lib/pkgconfig".

This means:  `sudo chown -R $(whoami) /usr/local/lib/pkgconfig`

Then you will need to link the files with this: `brew link yourLibrary`"

**Comment by RobAtticus** [comment]
Just checking back in to see if this is still an issue. Happy to help if that still doesn't work

**Comment by RobAtticus** [comment]
I'm going to close this out but please update if this is still a problem.
