### ISSUE TITLE
error: 'libpq-fe.h' file not found 

### ISSUE THREAD

**Issue by slavitch** [timescale/homebrew-tap#18]
brew install timescaledb
==> Installing timescaledb from timescale/tap
==> Downloading https://timescalereleases.blob.core.windows.net/homebrew/timescaledb-2.0.1.tar.lzma
Already downloaded: /Users/michael/Library/Caches/Homebrew/downloads/86a311958704c9e6161d1c81bf3816fde00fbd697c961ca015d0ad2283788a8a--timescaledb-2.0.1.tar.lzma
==> ./bootstrap -DREGRESS_CHECKS=OFF -DPROJECT_INSTALL_METHOD="brew"
==> cd ./build && make
Last 15 lines from /Users/michael/Library/Logs/Homebrew/timescaledb/02.build:
/tmp/timescaledb-20210216-87152-1xquj7x/timescaledb/tsl/src/remote/async.h:10:10: error: 'libpq-fe.h' file not found [clang-diagnostic-error]
#include <libpq-fe.h>
         ^
2 errors generated.
Error while processing /tmp/timescaledb-20210216-87152-1xquj7x/timescaledb/tsl/src/data_node.c.
make[2]: *** [tsl/src/CMakeFiles/timescaledb-tsl.dir/data_node.c.o] Error 1
error: unknown warning option '-Wno-format-truncation' [clang-diagnostic-unknown-warning-option]
/tmp/timescaledb-20210216-87152-1xquj7x/timescaledb/tsl/src/remote/dist_txn.h:11:10: error: 'libpq-fe.h' file not found [clang-diagnostic-error]
#include <libpq-fe.h>
         ^
2 errors generated.
Error while processing /tmp/timescaledb-20210216-87152-1xquj7x/timescaledb/tsl/src/init.c.
make[2]: *** [tsl/src/CMakeFiles/timescaledb-tsl.dir/init.c.o] Error 1
make[1]: *** [tsl/src/CMakeFiles/timescaledb-tsl.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/timescale/homebrew-tap/issues

**Comment by jonatas** [comment]
Similar to #22, I think we can safely close this issue.
