### ISSUE TITLE
Unable to install timescaledb-toolkit on MacOS Sonoma 14.0 with Intel

### ISSUE THREAD

**Issue by austinsmorris** [timescale/homebrew-tap#41]
brew install timescaledb-toolkit

==> Fetching timescale/tap/timescaledb-toolkit
==> Downloading https://github.com/tcdi/pgx/archive/refs/tags/v0.7.1.tar.gz
Already downloaded: /Users/austin/Library/Caches/Homebrew/downloads/5006eb8a6ad9d580cf1def141162253cf3566eae7ddfdf99ca5397ecbe2e9629--pgrx-0.7.1.tar.gz
==> Downloading https://github.com/timescale/timescaledb-toolkit/archive/refs/tags/1.16.0.tar.gz
Already downloaded: /Users/austin/Library/Caches/Homebrew/downloads/e1bd3e14f91601d22b589359c50ce0c58a03bb6cf2b4a647b0981549a90721f5--timescaledb-toolkit-1.16.0.tar.gz
==> Installing timescaledb-toolkit from timescale/tap
==> cargo install --path pgx/cargo-pgx
==> cargo pgx init --pg14 pg_config
==> cargo pgx package
Last 15 lines from /Users/austin/Library/Logs/Homebrew/timescaledb-toolkit/03.cargo:
  cargo:rerun-if-env-changed=PGX_TARGET_INFO_PATH_PG14
  cargo:rerun-if-env-changed=PGX_INCLUDEDIR_SERVER_PG14_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PGX_INCLUDEDIR_SERVER_PG14
  cargo:rerun-if-env-changed=PGX_INCLUDEDIR_SERVER_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PGX_INCLUDEDIR_SERVER
  cargo:rerun-if-env-changed=PGX_BINDGEN_NO_DETECT_INCLUDES_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PGX_BINDGEN_NO_DETECT_INCLUDES

  --- stderr
  build_paths=BuildPaths { manifest_dir: "/Users/austin/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/pgx-pg-sys-0.7.1", out_dir: "/private/tmp/timescaledb-toolkit-20231012-67716-1hlflpo/timescaledb-toolkit-1.16.0/target/release/build/pgx-pg-sys-294954ebbe11fd79/out", src_dir: "/Users/austin/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/pgx-pg-sys-0.7.1/src", shim_src: "/Users/austin/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/pgx-pg-sys-0.7.1/cshim", shim_dst: "/private/tmp/timescaledb-toolkit-20231012-67716-1hlflpo/timescaledb-toolkit-1.16.0/target/release/build/pgx-pg-sys-294954ebbe11fd79/out/cshim" }
  Generating bindings for pg14
  thread '<unnamed>' panicked at '"wait_struct_(unnamed_at_/Library/Developer/CommandLineTools/SDKs/MacOSX14_sdk/usr/include/sys/wait_h_199_2)" is not a valid Ident', /Users/austin/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.51/src/fallback.rs:752:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread 'main' panicked at 'thread panicked while generating bindings: Any { .. }', /Users/austin/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/pgx-pg-sys-0.7.1/build.rs:196:41
warning: build failed, waiting for other jobs to finish...

**Comment by bencoppock** [comment]
I'm having the same issue on MacOS Sonoma 14.0 on Apple Silicon.
