### ISSUE TITLE
Error at ./build && make

### ISSUE THREAD

**Issue by arpansharma** [timescale/homebrew-tap#5]
Last 15 lines from /Users/arpansharma/Library/Logs/Homebrew/timescaledb/02.build:
make[2]: *** [src/CMakeFiles/timescaledb.dir/catalog.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/CMakeFiles/timescaledb.dir/agg_bookend.c.o] Error 1
make[2]: *** [src/CMakeFiles/timescaledb.dir/cache.c.o] Error 1
make[2]: *** [src/CMakeFiles/timescaledb.dir/chunk_dispatch.c.o] Error 1
1 error generated.
1 error generated.
1 error generated.
make[2]: *** [src/CMakeFiles/timescaledb.dir/chunk_constraint.c.o] Error 1
make[2]: *** [src/CMakeFiles/timescaledb.dir/cache_invalidate.c.o] Error 1
make[2]: *** [src/CMakeFiles/timescaledb.dir/chunk.c.o] Error 1
1 error generated.
make[2]: *** [src/CMakeFiles/timescaledb.dir/chunk_adaptive.c.o] Error 1
make[1]: *** [src/CMakeFiles/timescaledb.dir/all] Error 2
make: *** [all] Error 2

**Comment by RobAtticus** [comment]
Is this still an issue?
